# Generated by Django 5.1.5 on 2025-01-28 12:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_destination_desc_destinationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='destinationdetail',
            name='place_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
