# Generated by Django 5.1.5 on 2025-02-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_comments_dislikes_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationdetail',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinationdetail',
            name='last_click_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='destinationdetail',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinationdetail',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
