# Generated by Django 5.1.5 on 2025-02-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_rename_destinationdetail_comments_destination_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(unique=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='destination_detail',
            new_name='DestinationDetail',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_ip',
        ),
        migrations.RemoveField(
            model_name='destinationdetail',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='destinationdetail',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='destinationdetail',
            name='last_click_time',
        ),
        migrations.RemoveField(
            model_name='destinationdetail',
            name='user_agent',
        ),
    ]
