# Generated by Django 5.1.5 on 2025-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_delete_ipaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='DestinationDetail',
            new_name='destination_detail',
        ),
    ]
